= Kursuslitteratur
v0.1, 31. juli 2015
:sectnums:
:sectanchors:

Kursuslitteraturn i kurset http://www.webcitation.org/6aQgDgKx9[Programmering
og problemløsning (PoP) 2015] er "Functional Programming Using F#", skrevet af
Michael R. Hansen og Hans Rischel (DTU), udgivet i 2013 af Cambridge University
Press, ISBN: 9781107019027.

== Find Bogen

En fysisk udgave af bogen kan købes fra
http://www.academicbooks.dk/functional-programming-using-f%2523/hans-rischel/michael-r-hansen/9781107019027[fakultetets
boghandel], på
http://www.amazon.co.uk/Functional-Programming-Using-Michael-Hansen/dp/1107684064/[Amazon],
eller
http://www.cambridge.org/dk/academic/subjects/computer-science/programming-languages-and-applied-logic/functional-programming-using-f[direkte
fra udgiveren].

PDF-udgaver af de enkelte kapitler ligger gratis tilgængelige for KU studerende
og ansatte.

Man skal blot være forbundet til eduroam og herefter følge linket:

http://dx.doi.org.ep.fjernadgang.kb.dk/10.1017/CBO9781139093996

Det kan betale sig at lægge en bogmærke for dette link.

Hvis ikke linket her virker, kan man prøve selv at finde bogen via REX:

. Gå ind på http://rex.kb.dk/.
. Søg efter "Functional Programming Using F#", tjek evt. efter forfatter,
  udgivelsesår og udgiver.
. Tryk "Online adgang".

== Hent Enkelte Kapitler

Betingelserne for brug af den digitale udgave findes her:
http://ebooks.cambridge.org.ep.fjernadgang.kb.dk/terms.jsf.

Bemærkelsesværdigt *må der kun hentes 600 PDF-filer* for en enkel bog *i
timen*.  Vi beder jer derfor om ikke at hente alle kapitler på en gang, men at
hente kapitlerne først når I har brug for dem. Det skal være en fair tjenneste
for os alle.

Ydermere, må de enkelte kapitler ikke samles, eller printes alle på en gang jf.
betingelserne.

== Supplerende (Avanceret) Litteratur

Bogen "Expert F# 3.0", skrevet af Don Syme, Adam Granicz, og Antonio
Cisternino, udgivet af Apress i 2012, ISBN: 978-1-4302-4650-3 (Print)
978-1-4302-4651-0 (Online), ligger også gratis tilgengælig for KU studerende og
ansatte:

http://link.springer.com/book/10.1007%2F978-1-4302-4651-0

Hvis ikke linket her virker, så prøv at finde bogen via REX.

Jf. http://link.springer.com/termsandconditions[betingelserne hos Springer] må
KU studerende og ansatte gerne hente og printe bogen til privat brug.
